user:
  outputs:
    default:
      account: MMCPNHY-DR52727
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: EBAY_PIPELINE
      password: Gh!kjZyH9.NKq3!
      retry_on_database_errors: true
      role: null
      schema: raw
      threads: 6
      type: snowflake
      user: Ethian
      warehouse: SNOWFLAKE_LEARNING_WH
  target: default
